sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-devtools-image .
  # list the installed packages (just for easier debugging)
  - docker run --rm -it yast-cluster-image rpm -qa | sort

script:
  # the "yast-travis-cpp" script is included in the base yastdevel/cpp image
  # see https://github.com/yast/docker-yast-cpp/blob/master/yast-travis-cpp
  - docker run -it yast-devtools-image yast-travis-cpp
